version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"  # or whatever Vite uses
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000  # Or adjust to proxy setup
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=96eabd97e810ba42dda9b91960aef53b0622166ef1b08500a3d48411e8fc54b3
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
